import type { SkillCategory } from "@/generated/prisma/enums";

export type SkillDefinition = { name: string; category: SkillCategory; aliases?: string[] };

/**
 * Catalogue de compétences (référentiel interne).
 * Utilisé pour normaliser les offres, les profils et les CV.
 */
export const SKILL_CATALOG: SkillDefinition[] = [
  // ── Langages ──
  { name: "JavaScript", category: "TECH", aliases: ["js", "ecmascript"] },
  { name: "TypeScript", category: "TECH", aliases: ["ts"] },
  { name: "Python", category: "TECH" },
  { name: "Java", category: "TECH" },
  { name: "C#", category: "TECH", aliases: ["csharp", "c sharp"] },
  { name: ".NET", category: "TECH", aliases: ["dotnet", "asp.net", "asp net"] },
  { name: "PHP", category: "TECH" },
  { name: "C++", category: "TECH", aliases: ["cpp"] },
  { name: "C", category: "TECH", aliases: ["langage c"] },
  { name: "Go", category: "TECH", aliases: ["golang"] },
  { name: "Rust", category: "TECH" },
  { name: "Kotlin", category: "TECH" },
  { name: "Swift", category: "TECH" },
  { name: "Ruby", category: "TECH", aliases: ["ruby on rails", "rails"] },
  { name: "SQL", category: "TECH", aliases: ["pl/sql", "t-sql"] },
  { name: "HTML", category: "TECH", aliases: ["html5"] },
  { name: "CSS", category: "TECH", aliases: ["css3", "sass", "scss"] },
  { name: "Bash", category: "TECH", aliases: ["shell", "scripting shell"] },
  { name: "PowerShell", category: "TECH" },
  // ── Frameworks & libs ──
  { name: "React", category: "TECH", aliases: ["reactjs", "react.js"] },
  { name: "Next.js", category: "TECH", aliases: ["nextjs", "next"] },
  { name: "Vue.js", category: "TECH", aliases: ["vue", "vuejs", "nuxt"] },
  { name: "Angular", category: "TECH", aliases: ["angularjs"] },
  { name: "Svelte", category: "TECH" },
  { name: "Node.js", category: "TECH", aliases: ["node", "nodejs", "express", "nestjs", "nest"] },
  { name: "Spring", category: "TECH", aliases: ["spring boot", "springboot"] },
  { name: "Symfony", category: "TECH" },
  { name: "Laravel", category: "TECH" },
  { name: "Django", category: "TECH" },
  { name: "Flask", category: "TECH" },
  { name: "FastAPI", category: "TECH" },
  { name: "React Native", category: "TECH" },
  { name: "Flutter", category: "TECH", aliases: ["dart"] },
  { name: "Android", category: "TECH" },
  { name: "iOS", category: "TECH" },
  { name: "Tailwind CSS", category: "TECH", aliases: ["tailwind"] },
  { name: "GraphQL", category: "TECH" },
  { name: "REST API", category: "TECH", aliases: ["api rest", "rest", "api"] },
  { name: "WordPress", category: "TOOL" },
  { name: "Shopify", category: "TOOL" },
  { name: "Prestashop", category: "TOOL" },
  // ── Data ──
  { name: "Pandas", category: "TECH" },
  { name: "NumPy", category: "TECH" },
  { name: "Machine Learning", category: "TECH", aliases: ["ml", "apprentissage automatique", "scikit-learn", "sklearn"] },
  { name: "Deep Learning", category: "TECH", aliases: ["tensorflow", "pytorch", "keras"] },
  { name: "Data Analysis", category: "TECH", aliases: ["analyse de données", "data analyse", "analyse de donnees"] },
  { name: "Data Engineering", category: "TECH", aliases: ["etl", "pipeline de données", "data pipeline"] },
  { name: "Power BI", category: "TOOL", aliases: ["powerbi"] },
  { name: "Tableau", category: "TOOL" },
  { name: "Looker", category: "TOOL", aliases: ["looker studio", "data studio"] },
  { name: "Excel", category: "TOOL", aliases: ["excel avancé", "tableur", "vba"] },
  { name: "Spark", category: "TECH", aliases: ["pyspark", "apache spark"] },
  { name: "Airflow", category: "TOOL" },
  { name: "dbt", category: "TOOL" },
  { name: "Snowflake", category: "TOOL" },
  { name: "BigQuery", category: "TOOL" },
  { name: "Databricks", category: "TOOL" },
  { name: "Statistiques", category: "DOMAIN", aliases: ["statistique", "statistics"] },
  { name: "LLM", category: "TECH", aliases: ["ia générative", "genai", "gen ai", "prompt engineering", "rag"] },
  // ── Bases de données ──
  { name: "PostgreSQL", category: "TECH", aliases: ["postgres", "postgresql"] },
  { name: "MySQL", category: "TECH", aliases: ["mariadb"] },
  { name: "MongoDB", category: "TECH", aliases: ["mongo"] },
  { name: "Redis", category: "TECH" },
  { name: "Elasticsearch", category: "TECH", aliases: ["elastic", "opensearch"] },
  { name: "Oracle", category: "TECH", aliases: ["oracle db"] },
  { name: "SQL Server", category: "TECH", aliases: ["mssql", "microsoft sql server"] },
  // ── Infra / Cloud / DevOps ──
  { name: "Linux", category: "TECH", aliases: ["debian", "ubuntu", "red hat", "centos"] },
  { name: "Windows Server", category: "TECH", aliases: ["windows serveur"] },
  { name: "Active Directory", category: "TECH", aliases: ["ad", "azure ad", "entra id"] },
  { name: "Réseaux", category: "TECH", aliases: ["réseau", "tcp/ip", "lan", "wan", "vlan", "cisco", "ccna", "routage", "switching", "network"] },
  { name: "Docker", category: "TOOL", aliases: ["conteneurisation", "containers"] },
  { name: "Kubernetes", category: "TOOL", aliases: ["k8s"] },
  { name: "AWS", category: "TOOL", aliases: ["amazon web services"] },
  { name: "Azure", category: "TOOL", aliases: ["microsoft azure"] },
  { name: "GCP", category: "TOOL", aliases: ["google cloud", "google cloud platform"] },
  { name: "Terraform", category: "TOOL", aliases: ["iac", "infrastructure as code"] },
  { name: "Ansible", category: "TOOL" },
  { name: "CI/CD", category: "TOOL", aliases: ["ci cd", "gitlab ci", "github actions", "jenkins", "intégration continue"] },
  { name: "Git", category: "TOOL", aliases: ["github", "gitlab", "bitbucket", "versioning"] },
  { name: "Virtualisation", category: "TECH", aliases: ["vmware", "hyper-v", "proxmox", "vsphere"] },
  { name: "Support utilisateur", category: "DOMAIN", aliases: ["support technique", "helpdesk", "support n1", "support n2", "hotline", "assistance utilisateurs", "glpi"] },
  { name: "ITIL", category: "DOMAIN" },
  { name: "Monitoring", category: "TOOL", aliases: ["supervision", "grafana", "prometheus", "zabbix", "datadog", "centreon"] },
  { name: "Office 365", category: "TOOL", aliases: ["microsoft 365", "m365", "o365", "sharepoint", "teams", "intune"] },
  // ── Cybersécurité ──
  { name: "Cybersécurité", category: "DOMAIN", aliases: ["cyber sécurité", "sécurité informatique", "cyber", "sécurité des si", "ssi"] },
  { name: "Pentest", category: "TECH", aliases: ["test d'intrusion", "tests d'intrusion", "ethical hacking", "red team"] },
  { name: "SOC", category: "DOMAIN", aliases: ["security operations center", "blue team", "analyste soc"] },
  { name: "SIEM", category: "TOOL", aliases: ["splunk", "qradar", "sentinel", "elk"] },
  { name: "ISO 27001", category: "DOMAIN", aliases: ["iso27001", "27001"] },
  { name: "Cryptographie", category: "TECH", aliases: ["chiffrement", "pki"] },
  { name: "Firewall", category: "TECH", aliases: ["pare-feu", "fortinet", "palo alto", "stormshield"] },
  { name: "RGPD", category: "DOMAIN", aliases: ["gdpr", "protection des données"] },
  { name: "EBIOS", category: "DOMAIN", aliases: ["analyse de risques", "gestion des risques"] },
  // ── Produit / Méthodes ──
  { name: "Agile", category: "DOMAIN", aliases: ["scrum", "kanban", "méthodes agiles", "méthode agile", "safe"] },
  { name: "Gestion de projet", category: "DOMAIN", aliases: ["project management", "pilotage de projet", "chef de projet", "planification", "gantt"] },
  { name: "Jira", category: "TOOL", aliases: ["confluence", "atlassian"] },
  { name: "Notion", category: "TOOL" },
  { name: "Product Management", category: "DOMAIN", aliases: ["product owner", "product manager", "gestion de produit", "roadmap", "backlog"] },
  { name: "UX Research", category: "DOMAIN", aliases: ["recherche utilisateur", "user research", "tests utilisateurs"] },
  { name: "Tests logiciels", category: "TECH", aliases: ["qa", "tests automatisés", "cypress", "playwright", "selenium", "jest", "tests unitaires", "recette"] },
  // ── Design ──
  { name: "Figma", category: "TOOL" },
  { name: "Adobe Photoshop", category: "TOOL", aliases: ["photoshop"] },
  { name: "Adobe Illustrator", category: "TOOL", aliases: ["illustrator"] },
  { name: "Adobe InDesign", category: "TOOL", aliases: ["indesign"] },
  { name: "Adobe Premiere", category: "TOOL", aliases: ["premiere pro", "montage vidéo", "after effects", "davinci resolve"] },
  { name: "UX/UI Design", category: "DOMAIN", aliases: ["ux", "ui", "ux design", "ui design", "design d'interface", "wireframe", "prototypage", "maquettage"] },
  { name: "Design graphique", category: "DOMAIN", aliases: ["graphisme", "identité visuelle", "pao", "infographie"] },
  { name: "Motion design", category: "DOMAIN", aliases: ["animation", "motion"] },
  { name: "Canva", category: "TOOL" },
  // ── Marketing / Communication ──
  { name: "SEO", category: "DOMAIN", aliases: ["référencement naturel", "référencement", "search engine optimization"] },
  { name: "SEA", category: "DOMAIN", aliases: ["google ads", "adwords", "référencement payant", "sem"] },
  { name: "Social media", category: "DOMAIN", aliases: ["réseaux sociaux", "community management", "community manager", "instagram", "tiktok", "linkedin", "meta ads"] },
  { name: "Content marketing", category: "DOMAIN", aliases: ["rédaction web", "rédaction de contenu", "copywriting", "création de contenu", "brand content", "storytelling"] },
  { name: "Emailing", category: "DOMAIN", aliases: ["email marketing", "newsletter", "mailchimp", "brevo", "sendinblue", "marketing automation"] },
  { name: "Google Analytics", category: "TOOL", aliases: ["ga4", "analytics", "matomo", "web analytics"] },
  { name: "HubSpot", category: "TOOL" },
  { name: "Salesforce", category: "TOOL" },
  { name: "CRM", category: "TOOL", aliases: ["gestion de la relation client", "pipedrive", "zoho"] },
  { name: "Growth marketing", category: "DOMAIN", aliases: ["growth", "growth hacking", "acquisition", "acquisition digitale"] },
  { name: "Marketing digital", category: "DOMAIN", aliases: ["webmarketing", "marketing numérique", "stratégie digitale", "digital marketing"] },
  { name: "Communication", category: "DOMAIN", aliases: ["communication interne", "communication externe", "relations presse", "plan de communication", "communication corporate"] },
  { name: "Événementiel", category: "DOMAIN", aliases: ["organisation d'événements", "événements", "evenementiel", "salons"] },
  { name: "Études de marché", category: "DOMAIN", aliases: ["étude de marché", "veille concurrentielle", "benchmark", "veille"] },
  { name: "E-commerce", category: "DOMAIN", aliases: ["marketplace", "amazon", "ecommerce"] },
  { name: "Merchandising", category: "DOMAIN", aliases: ["merch", "mise en rayon"] },
  // ── Commerce ──
  { name: "Prospection", category: "DOMAIN", aliases: ["prospection commerciale", "prospection téléphonique", "phoning", "cold calling", "outbound"] },
  { name: "Négociation", category: "DOMAIN", aliases: ["négociation commerciale", "closing"] },
  { name: "Vente", category: "DOMAIN", aliases: ["techniques de vente", "vente b2b", "vente b2c", "commercial", "développement commercial", "business development"] },
  { name: "Relation client", category: "DOMAIN", aliases: ["service client", "satisfaction client", "fidélisation", "suivi client", "gestion de portefeuille clients", "customer success"] },
  { name: "Gestion de compte", category: "DOMAIN", aliases: ["account management", "key account", "grands comptes"] },
  { name: "Réponse à appels d'offres", category: "DOMAIN", aliases: ["appels d'offres", "appel d'offres", "devis", "chiffrage"] },
  // ── RH ──
  { name: "Recrutement", category: "DOMAIN", aliases: ["sourcing", "entretiens de recrutement", "talent acquisition", "chasse de tête", "onboarding"] },
  { name: "Gestion de la paie", category: "DOMAIN", aliases: ["paie", "payroll", "silae", "sage paie", "adp"] },
  { name: "Administration du personnel", category: "DOMAIN", aliases: ["adp", "gestion administrative du personnel", "contrats de travail", "dpae"] },
  { name: "Droit du travail", category: "DOMAIN", aliases: ["droit social", "relations sociales", "cse"] },
  { name: "Formation", category: "DOMAIN", aliases: ["plan de formation", "ingénierie de formation", "gpec", "développement des compétences"] },
  { name: "SIRH", category: "TOOL", aliases: ["workday", "successfactors", "lucca", "payfit"] },
  { name: "Marque employeur", category: "DOMAIN", aliases: ["employer branding", "qvt"] },
  // ── Finance / Compta ──
  { name: "Comptabilité générale", category: "DOMAIN", aliases: ["comptabilité", "compta", "écritures comptables", "saisie comptable", "clôture", "bilan"] },
  { name: "Comptabilité analytique", category: "DOMAIN", aliases: ["analytique", "coûts de revient"] },
  { name: "Contrôle de gestion", category: "DOMAIN", aliases: ["contrôleur de gestion", "reporting financier", "budget", "budgets", "prévisionnel", "kpi", "tableaux de bord"] },
  { name: "Analyse financière", category: "DOMAIN", aliases: ["finance d'entreprise", "corporate finance", "modélisation financière", "valorisation"] },
  { name: "Audit", category: "DOMAIN", aliases: ["audit financier", "commissariat aux comptes", "audit interne", "contrôle interne"] },
  { name: "Fiscalité", category: "DOMAIN", aliases: ["tva", "déclarations fiscales", "impôts", "liasse fiscale"] },
  { name: "Trésorerie", category: "DOMAIN", aliases: ["cash management", "gestion de trésorerie", "rapprochement bancaire"] },
  { name: "Sage", category: "TOOL", aliases: ["sage 100", "sage x3", "cegid", "ebp", "pennylane"] },
  { name: "SAP", category: "TOOL", aliases: ["sap fi", "sap co", "sap mm", "sap sd", "s/4hana"] },
  { name: "ERP", category: "TOOL", aliases: ["progiciel", "odoo", "dynamics", "microsoft dynamics", "sage x3"] },
  { name: "Facturation", category: "DOMAIN", aliases: ["facturation clients", "recouvrement", "relances clients", "comptabilité clients", "comptabilité fournisseurs"] },
  { name: "Assurance", category: "DOMAIN", aliases: ["gestion des sinistres", "iard", "prévoyance", "mutuelle", "assurance vie"] },
  { name: "Banque", category: "DOMAIN", aliases: ["produits bancaires", "crédit", "conseiller bancaire", "conformité bancaire", "kyc", "lcb-ft"] },
  // ── Juridique ──
  { name: "Droit des affaires", category: "DOMAIN", aliases: ["droit des sociétés", "droit commercial", "contrats", "rédaction de contrats"] },
  { name: "Conformité", category: "DOMAIN", aliases: ["compliance", "réglementaire", "veille juridique"] },
  // ── Industrie / Ingénierie ──
  { name: "CAO", category: "TOOL", aliases: ["solidworks", "catia", "autocad", "dao", "conception assistée", "inventor", "creo", "revit"] },
  { name: "Mécanique", category: "DOMAIN", aliases: ["conception mécanique", "génie mécanique", "mécanique industrielle", "usinage"] },
  { name: "Électronique", category: "DOMAIN", aliases: ["électronique embarquée", "cartes électroniques", "pcb", "vhdl", "fpga"] },
  { name: "Électrotechnique", category: "DOMAIN", aliases: ["électricité industrielle", "génie électrique", "habilitation électrique", "câblage"] },
  { name: "Automatisme", category: "DOMAIN", aliases: ["automate", "automates", "siemens tia portal", "schneider", "plc", "supervision industrielle", "scada", "robotique"] },
  { name: "Maintenance industrielle", category: "DOMAIN", aliases: ["maintenance", "gmao", "maintenance préventive", "maintenance curative", "dépannage"] },
  { name: "Lean management", category: "DOMAIN", aliases: ["lean", "amélioration continue", "5s", "kaizen", "six sigma", "smed"] },
  { name: "Méthodes industrialisation", category: "DOMAIN", aliases: ["méthodes", "industrialisation", "gammes", "temps et méthodes", "process"] },
  { name: "Qualité", category: "DOMAIN", aliases: ["assurance qualité", "iso 9001", "contrôle qualité", "non-conformités", "audit qualité", "qhse", "hse", "sécurité au travail", "amdec", "8d"] },
  { name: "Supply chain", category: "DOMAIN", aliases: ["logistique", "approvisionnement", "gestion des stocks", "planification de production", "ordonnancement", "transport", "flux", "wms"] },
  { name: "Achats", category: "DOMAIN", aliases: ["acheteur", "sourcing fournisseurs", "négociation fournisseurs", "gestion fournisseurs"] },
  { name: "Thermique", category: "DOMAIN", aliases: ["énergétique", "cvc", "génie climatique", "efficacité énergétique", "fluides"] },
  { name: "Matériaux", category: "DOMAIN", aliases: ["composites", "métallurgie", "plasturgie"] },
  { name: "Bureau d'études", category: "DOMAIN", aliases: ["études techniques", "dimensionnement", "calcul de structures", "plans"] },
  { name: "BIM", category: "TOOL", aliases: ["maquette numérique"] },
  // ── Gestion / Administratif ──
  { name: "Gestion administrative", category: "DOMAIN", aliases: ["administratif", "secrétariat", "accueil", "gestion du courrier", "classement", "saisie"] },
  { name: "Pack Office", category: "TOOL", aliases: ["word", "powerpoint", "outlook", "office", "suite office", "microsoft office", "google workspace", "google sheets"] },
  { name: "Gestion des stocks", category: "DOMAIN", aliases: ["inventaire", "réception de marchandises"] },
  { name: "Rédaction", category: "SOFT", aliases: ["rédactionnel", "rédiger", "orthographe", "bonne orthographe", "qualités rédactionnelles"] },
  // ── Soft skills ──
  { name: "Autonomie", category: "SOFT", aliases: ["autonome"] },
  { name: "Rigueur", category: "SOFT", aliases: ["rigoureux", "rigoureuse", "organisation", "organisé", "organisée", "sens de l'organisation"] },
  { name: "Esprit d'équipe", category: "SOFT", aliases: ["travail en équipe", "collaboration", "collaboratif", "team player"] },
  { name: "Curiosité", category: "SOFT", aliases: ["curieux", "curieuse", "envie d'apprendre"] },
  { name: "Communication orale", category: "SOFT", aliases: ["aisance relationnelle", "sens du relationnel", "relationnel", "aisance orale", "prise de parole"] },
  { name: "Créativité", category: "SOFT", aliases: ["créatif", "créative", "force de proposition"] },
  { name: "Adaptabilité", category: "SOFT", aliases: ["flexibilité", "polyvalence", "polyvalent", "réactivité", "réactif"] },
  { name: "Résolution de problèmes", category: "SOFT", aliases: ["problem solving", "esprit d'analyse", "analyse", "esprit critique", "logique"] },
  { name: "Sens du service", category: "SOFT", aliases: ["orientation client", "sens du client", "écoute", "pédagogie"] },
  // ── Langues ──
  { name: "Anglais", category: "LANGUAGE", aliases: ["english", "anglais professionnel", "anglais courant", "toeic", "anglais technique", "bilingue anglais"] },
  { name: "Espagnol", category: "LANGUAGE", aliases: ["spanish", "español"] },
  { name: "Allemand", category: "LANGUAGE", aliases: ["german", "deutsch"] },
  { name: "Italien", category: "LANGUAGE", aliases: ["italian"] },
  { name: "Chinois", category: "LANGUAGE", aliases: ["mandarin"] },
  { name: "Portugais", category: "LANGUAGE" },
  { name: "Arabe", category: "LANGUAGE" },
];

/** Suggestions rapides par famille de métier (onboarding et profil visiteur). */
export const FAMILY_SKILL_SUGGESTIONS: Record<string, string[]> = {
  dev: ["JavaScript", "React", "Node.js", "SQL", "Git", "PHP", "Java", "Python"],
  data: ["SQL", "Python", "Power BI", "Excel", "Pandas", "Machine Learning"],
  cyber: ["Linux", "Réseaux", "Cybersécurité", "Python", "SIEM", "Pentest"],
  infra: ["Linux", "Windows Server", "Réseaux", "Active Directory", "Docker", "Support utilisateur"],
  marketing: ["SEO", "Social media", "Canva", "Google Analytics", "Emailing", "Content marketing"],
  communication: ["Communication", "Rédaction", "Canva", "Social media", "Événementiel"],
  sales: ["Prospection", "Négociation", "CRM", "Relation client", "Vente"],
  hr: ["Recrutement", "Pack Office", "Administration du personnel", "SIRH"],
  finance: ["Excel", "Contrôle de gestion", "Power BI", "Analyse financière"],
  accounting: ["Comptabilité générale", "Excel", "Sage", "Facturation"],
  design: ["Figma", "Adobe Photoshop", "Adobe Illustrator", "UX/UI Design"],
  industrial: ["CAO", "Mécanique", "Automatisme", "Lean management"],
  logistics: ["Supply chain", "Excel", "ERP", "Gestion des stocks"],
  quality: ["Qualité", "Lean management", "Excel", "Audit"],
  product: ["Agile", "Jira", "Product Management", "Figma"],
  "customer-support": ["Relation client", "CRM", "Pack Office", "Communication orale"],
  admin: ["Pack Office", "Gestion administrative", "Rédaction"],
  "retail-ops": ["Vente", "Merchandising", "Relation client"],
  project: ["Gestion de projet", "Agile", "Jira", "Pack Office"],
  purchasing: ["Achats", "Négociation", "Excel", "Anglais"],
  legal: ["Droit des affaires", "Conformité", "RGPD", "Rédaction"],
  health: ["Rigueur", "Sens du service"],
};
