/**
 * Entreprises de DÉMONSTRATION.
 * Toutes ces sociétés sont fictives (isDemo = true). Aucun nom, site ou contact
 * ne correspond à une organisation ou une personne réelle.
 */
import type { CompanySize } from "../../src/generated/prisma/enums";

export type SeedContact = { firstName: string; lastName: string; jobTitle: string; department?: string };

export type SeedCompany = {
  name: string;
  slug: string;
  sector: string;
  size: CompanySize;
  headcount: number;
  city: string;
  description: string;
  website: string;
  foundedYear: number;
  technologies: string[];
  jobFamilies: string[];
  hiresApprentices: boolean;
  apprenticeCountEstimate: number | null;
  isHiring: boolean;
  contacts: SeedContact[];
  otherLocations?: string[];
  /** Nombre d'offres à générer (0 = entreprise sans offre, visible seulement via le Radar). */
  jobsCount: number;
};

export const SEED_COMPANIES: SeedCompany[] = [
  // ─────────────── NANTES & AGGLO ───────────────
  {
    name: "Nova Systèmes", slug: "nova-systemes", sector: "consulting", size: "ETI", headcount: 1200, city: "Nantes",
    description: "ESN nantaise spécialisée dans la transformation digitale des banques et assureurs de l'Ouest. 1 200 consultants répartis entre Nantes, Rennes et Paris, une culture de l'apprentissage forte : 80 alternants accueillis chaque année.",
    website: "https://nova-systemes.example.com", foundedYear: 2004,
    technologies: ["java", "spring", "angular", "react", "aws", "kubernetes", "sql"],
    jobFamilies: ["dev", "data", "cyber", "infra", "product"], hiresApprentices: true, apprenticeCountEstimate: 80, isHiring: true,
    contacts: [
      { firstName: "Marie", lastName: "Dupont", jobTitle: "Talent Acquisition Specialist", department: "Ressources humaines" },
      { firstName: "Julien", lastName: "Renaud", jobTitle: "Directeur d'agence Nantes" },
      { firstName: "Camille", lastName: "Lefèvre", jobTitle: "Tech Lead Java", department: "Delivery" },
    ],
    otherLocations: ["Rennes", "Paris"], jobsCount: 6,
  },
  {
    name: "Atlantic Cloud", slug: "atlantic-cloud", sector: "tech", size: "PME", headcount: 85, city: "Saint-Herblain",
    description: "Hébergeur cloud souverain basé à Saint-Herblain. Infrastructure Kubernetes, stockage objet et services managés pour les PME du Grand Ouest. Équipe de 85 personnes, ambiance startup et datacenters locaux.",
    website: "https://atlantic-cloud.example.com", foundedYear: 2015,
    technologies: ["kubernetes", "linux", "terraform", "go", "python", "monitoring", "docker"],
    jobFamilies: ["infra", "dev", "cyber", "customer-support"], hiresApprentices: true, apprenticeCountEstimate: 6, isHiring: true,
    contacts: [
      { firstName: "Thomas", lastName: "Guérin", jobTitle: "Responsable infrastructure", department: "Ops" },
      { firstName: "Inès", lastName: "Morel", jobTitle: "Chargée RH & recrutement" },
    ],
    jobsCount: 4,
  },
  {
    name: "Loire Digital", slug: "loire-digital", sector: "digital-agency", size: "PME", headcount: 42, city: "Nantes",
    description: "Agence digitale nantaise : sites e-commerce, applications mobiles et campagnes d'acquisition pour des marques régionales. Ateliers créatifs, télétravail 2 jours par semaine et alternants intégrés dans les équipes projet.",
    website: "https://loire-digital.example.com", foundedYear: 2011,
    technologies: ["react", "next-js", "php", "symfony", "shopify", "figma", "seo"],
    jobFamilies: ["dev", "design", "marketing", "product"], hiresApprentices: true, apprenticeCountEstimate: 5, isHiring: true,
    contacts: [
      { firstName: "Léa", lastName: "Bourgeois", jobTitle: "Lead développeuse web" },
      { firstName: "Karim", lastName: "Benali", jobTitle: "Directeur associé" },
    ],
    jobsCount: 4,
  },
  {
    name: "Crédit Atlantique Mutuel", slug: "credit-atlantique-mutuel", sector: "banking-insurance", size: "GE", headcount: 6500, city: "Nantes",
    description: "Banque coopérative régionale, 6 500 collaborateurs et 400 agences dans l'Ouest. Programmes d'alternance structurés dans les métiers bancaires, la data, l'IT et la conformité, avec un parcours d'intégration dédié.",
    website: "https://credit-atlantique-mutuel.example.com", foundedYear: 1962,
    technologies: ["java", "sql", "power-bi", "sap", "salesforce"],
    jobFamilies: ["finance", "customer-support", "data", "dev", "legal", "sales", "hr"], hiresApprentices: true, apprenticeCountEstimate: 150, isHiring: true,
    contacts: [
      { firstName: "Sophie", lastName: "Marchand", jobTitle: "Responsable campus & alternance", department: "Ressources humaines" },
      { firstName: "Nicolas", lastName: "Petit", jobTitle: "Directeur de la data", department: "Direction financière" },
    ],
    otherLocations: ["Angers", "Rennes", "La Roche-sur-Yon", "Vannes"], jobsCount: 7,
  },
  {
    name: "Assurances de l'Estuaire", slug: "assurances-de-l-estuaire", sector: "banking-insurance", size: "ETI", headcount: 900, city: "Nantes",
    description: "Assureur mutualiste spécialisé dans la protection des professionnels et des artisans. Siège à Nantes, plateforme de gestion à Angers. Recrute régulièrement des alternants en gestion de sinistres, marketing et systèmes d'information.",
    website: "https://assurances-estuaire.example.com", foundedYear: 1978,
    technologies: ["sql", "power-bi", "salesforce", "java"],
    jobFamilies: ["customer-support", "marketing", "data", "dev", "legal", "accounting"], hiresApprentices: true, apprenticeCountEstimate: 30, isHiring: true,
    contacts: [{ firstName: "Élodie", lastName: "Garnier", jobTitle: "Chargée de recrutement", department: "RH" }],
    otherLocations: ["Angers"], jobsCount: 4,
  },
  {
    name: "Chantiers de l'Estuaire", slug: "chantiers-de-l-estuaire", sector: "aerospace-naval", size: "GE", headcount: 5200, city: "Saint-Nazaire",
    description: "Constructeur naval de Saint-Nazaire : paquebots, navires militaires et éoliennes offshore. 5 200 salariés, un centre de formation interne et plus de 200 alternants par an dans les métiers de l'ingénierie, de la production, de la supply chain et de la qualité.",
    website: "https://chantiers-estuaire.example.com", foundedYear: 1861,
    technologies: ["cao", "sap", "automatisme", "lean-management", "bim"],
    jobFamilies: ["industrial", "quality", "logistics", "purchasing", "project", "hr", "infra"], hiresApprentices: true, apprenticeCountEstimate: 220, isHiring: true,
    contacts: [
      { firstName: "Pierre", lastName: "Le Goff", jobTitle: "Responsable alternance & relations écoles", department: "RH" },
      { firstName: "Anaïs", lastName: "Rolland", jobTitle: "Responsable bureau d'études structure" },
    ],
    otherLocations: ["Nantes"], jobsCount: 6,
  },
  {
    name: "Aéro Composites Ouest", slug: "aero-composites-ouest", sector: "aerospace-naval", size: "ETI", headcount: 1400, city: "Saint-Nazaire",
    description: "Sous-traitant aéronautique de rang 1 : pièces composites et assemblages de fuselage. Sites à Saint-Nazaire, Nantes et Cholet. Fort investissement dans l'automatisation et la qualité.",
    website: "https://aero-composites-ouest.example.com", foundedYear: 1989,
    technologies: ["cao", "materiaux", "qualite", "automatisme", "sap"],
    jobFamilies: ["industrial", "quality", "logistics", "purchasing"], hiresApprentices: true, apprenticeCountEstimate: 40, isHiring: true,
    contacts: [{ firstName: "Maxime", lastName: "Chevalier", jobTitle: "Chargé RH", department: "Ressources humaines" }],
    otherLocations: ["Nantes", "Cholet"], jobsCount: 4,
  },
  {
    name: "La Fabrique Marketing", slug: "la-fabrique-marketing", sector: "digital-agency", size: "TPE", headcount: 8, city: "Rezé",
    description: "Petite agence de marketing digital à Rezé : SEO, social media et contenus pour les commerçants et PME nantaises. Équipe soudée de 8 personnes, un alternant chaque année, beaucoup d'autonomie.",
    website: "https://la-fabrique-marketing.example.com", foundedYear: 2018,
    technologies: ["seo", "google-analytics", "social-media", "canva", "wordpress", "emailing"],
    jobFamilies: ["marketing", "communication", "design"], hiresApprentices: true, apprenticeCountEstimate: 1, isHiring: false,
    contacts: [{ firstName: "Nora", lastName: "Haddad", jobTitle: "Fondatrice & directrice" }],
    jobsCount: 1,
  },
  {
    name: "Vertou Bio Distribution", slug: "vertou-bio-distribution", sector: "retail", size: "PME", headcount: 160, city: "Vertou",
    description: "Réseau de 12 magasins bio indépendants en Loire-Atlantique et Vendée, siège à Vertou. Recrute des alternants en vente, management de rayon, logistique et marketing.",
    website: "https://vertou-bio.example.com", foundedYear: 2006,
    technologies: ["erp", "excel", "merchandising"],
    jobFamilies: ["retail-ops", "sales", "logistics", "marketing", "accounting"], hiresApprentices: true, apprenticeCountEstimate: 8, isHiring: true,
    contacts: [{ firstName: "Vincent", lastName: "Lemoine", jobTitle: "Directeur des opérations" }],
    otherLocations: ["Nantes", "La Roche-sur-Yon"], jobsCount: 3,
  },
  {
    name: "Carquefou Robotique", slug: "carquefou-robotique", sector: "industry", size: "PME", headcount: 120, city: "Carquefou",
    description: "Intégrateur de robots industriels et de lignes automatisées pour l'agroalimentaire et l'aéronautique. Bureau d'études, atelier et équipe de mise en service. Alternants ingénieurs et techniciens bienvenus.",
    website: "https://carquefou-robotique.example.com", foundedYear: 1996,
    technologies: ["automatisme", "cao", "electrotechnique", "python", "monitoring"],
    jobFamilies: ["industrial", "dev", "project", "sales"], hiresApprentices: true, apprenticeCountEstimate: 7, isHiring: true,
    contacts: [{ firstName: "Hélène", lastName: "Baudry", jobTitle: "Responsable bureau d'études automatisme" }],
    jobsCount: 3,
  },
  {
    name: "Orvault Santé Services", slug: "orvault-sante-services", sector: "health", size: "PME", headcount: 210, city: "Orvault",
    description: "Groupe de cliniques et centres de soins de l'agglomération nantaise. Fonctions support (RH, comptabilité, communication, informatique) basées à Orvault.",
    website: "https://orvault-sante.example.com", foundedYear: 1999,
    technologies: ["pack-office", "sage", "sirh"],
    jobFamilies: ["hr", "accounting", "communication", "admin", "infra"], hiresApprentices: true, apprenticeCountEstimate: 5, isHiring: false,
    contacts: [{ firstName: "Claire", lastName: "Fontaine", jobTitle: "Directrice des ressources humaines" }],
    jobsCount: 2,
  },
  {
    name: "Breizh Data", slug: "breizh-data", sector: "tech", size: "PME", headcount: 55, city: "Nantes",
    description: "Startup data & IA : plateformes de prévision de la demande pour la grande distribution. Nantes et Rennes, stack Python moderne, culture produit, 40 % de l'équipe issue de l'alternance.",
    website: "https://breizh-data.example.com", foundedYear: 2019,
    technologies: ["python", "machine-learning", "sql", "airflow", "dbt", "aws", "react", "llm"],
    jobFamilies: ["data", "dev", "product", "sales"], hiresApprentices: true, apprenticeCountEstimate: 6, isHiring: true,
    contacts: [
      { firstName: "Yann", lastName: "Le Bris", jobTitle: "CTO & cofondateur" },
      { firstName: "Manon", lastName: "Simon", jobTitle: "Head of People" },
    ],
    otherLocations: ["Rennes"], jobsCount: 4,
  },
  {
    name: "Nantes Métropole Habitat Demo", slug: "nantes-metropole-habitat-demo", sector: "public", size: "ETI", headcount: 480, city: "Nantes",
    description: "Bailleur social fictif de la métropole nantaise. Alternances en gestion locative, communication, informatique et comptabilité.",
    website: "https://nmh-demo.example.com", foundedYear: 1913,
    technologies: ["pack-office", "sap", "power-bi"],
    jobFamilies: ["admin", "communication", "accounting", "infra", "customer-support"], hiresApprentices: true, apprenticeCountEstimate: 12, isHiring: true,
    contacts: [{ firstName: "Bruno", lastName: "Martel", jobTitle: "Chargé de développement RH" }],
    jobsCount: 2,
  },
  // ─────────────── ANGERS / CHOLET / LE MANS / LAVAL / LA ROCHE ───────────────
  {
    name: "Végépolis Innovation", slug: "vegepolis-innovation", sector: "food-agri", size: "ETI", headcount: 650, city: "Angers",
    description: "Groupe semencier et agroalimentaire angevin. Laboratoires, usine de conditionnement et fonctions support. Alternants en qualité, supply chain, marketing et informatique.",
    website: "https://vegepolis.example.com", foundedYear: 1971,
    technologies: ["sap", "qualite", "excel", "power-bi", "lean-management"],
    jobFamilies: ["quality", "logistics", "marketing", "data", "purchasing", "hr"], hiresApprentices: true, apprenticeCountEstimate: 25, isHiring: true,
    contacts: [{ firstName: "Aurélie", lastName: "Gauthier", jobTitle: "Responsable recrutement", department: "RH" }],
    otherLocations: ["Cholet"], jobsCount: 4,
  },
  {
    name: "Anjou Web Studio", slug: "anjou-web-studio", sector: "digital-agency", size: "PME", headcount: 24, city: "Angers",
    description: "Studio angevin de création web et mobile. Clients viticoles, tourisme et industrie locale. Environnement React / Node, méthode agile, deux alternants développeurs chaque année.",
    website: "https://anjou-web-studio.example.com", foundedYear: 2014,
    technologies: ["react", "node-js", "typescript", "wordpress", "figma"],
    jobFamilies: ["dev", "design", "marketing"], hiresApprentices: true, apprenticeCountEstimate: 2, isHiring: true,
    contacts: [{ firstName: "Romain", lastName: "Delaunay", jobTitle: "Gérant & lead développeur" }],
    jobsCount: 2,
  },
  {
    name: "Cholet Mode Groupe", slug: "cholet-mode-groupe", sector: "retail", size: "ETI", headcount: 800, city: "Cholet",
    description: "Groupe textile choletais : marques de mode enfant et sport, e-commerce et 90 boutiques. Alternances en e-commerce, achats, logistique et contrôle de gestion.",
    website: "https://cholet-mode.example.com", foundedYear: 1958,
    technologies: ["shopify", "e-commerce", "sap", "google-analytics", "excel"],
    jobFamilies: ["marketing", "purchasing", "logistics", "finance", "retail-ops"], hiresApprentices: true, apprenticeCountEstimate: 18, isHiring: true,
    contacts: [{ firstName: "Laurence", lastName: "Boisseau", jobTitle: "DRH adjointe" }],
    jobsCount: 3,
  },
  {
    name: "Sarthe Automotive Systems", slug: "sarthe-automotive-systems", sector: "automotive", size: "ETI", headcount: 1100, city: "Le Mans",
    description: "Équipementier automobile manceau : systèmes de freinage et électronique embarquée. Centre R&D au Mans, usine à Laval. Alternances en ingénierie, qualité, méthodes et achats.",
    website: "https://sarthe-automotive.example.com", foundedYear: 1982,
    technologies: ["cao", "electronique", "c", "python", "qualite", "sap"],
    jobFamilies: ["industrial", "quality", "purchasing", "logistics", "dev"], hiresApprentices: true, apprenticeCountEstimate: 35, isHiring: true,
    contacts: [
      { firstName: "Stéphane", lastName: "Roux", jobTitle: "Responsable développement RH", department: "RH" },
      { firstName: "Julie", lastName: "Mercier", jobTitle: "Responsable R&D électronique" },
    ],
    otherLocations: ["Laval"], jobsCount: 4,
  },
  {
    name: "Mutuelle du Maine", slug: "mutuelle-du-maine", sector: "banking-insurance", size: "ETI", headcount: 700, city: "Le Mans",
    description: "Mutuelle santé et prévoyance basée au Mans. Centre de relation client, direction financière et DSI recrutent des alternants chaque rentrée.",
    website: "https://mutuelle-du-maine.example.com", foundedYear: 1947,
    technologies: ["sql", "power-bi", "salesforce", "java"],
    jobFamilies: ["customer-support", "finance", "accounting", "dev", "data", "marketing"], hiresApprentices: true, apprenticeCountEstimate: 20, isHiring: true,
    contacts: [{ firstName: "Isabelle", lastName: "Perrin", jobTitle: "Chargée de mission alternance" }],
    jobsCount: 3,
  },
  {
    name: "Laval Réalité Virtuelle", slug: "laval-realite-virtuelle", sector: "tech", size: "PME", headcount: 38, city: "Laval",
    description: "Studio lavallois de réalité virtuelle et augmentée pour l'industrie et la formation. Unity, 3D temps réel et R&D. Petite équipe passionnée, alternants ingénieurs et développeurs.",
    website: "https://laval-rv.example.com", foundedYear: 2012,
    technologies: ["c#", "unity", "c++", "python", "figma"],
    jobFamilies: ["dev", "design", "product", "sales"], hiresApprentices: true, apprenticeCountEstimate: 3, isHiring: false,
    contacts: [{ firstName: "Antoine", lastName: "Rivière", jobTitle: "Directeur technique" }],
    jobsCount: 2,
  },
  {
    name: "Vendée Énergies Marines", slug: "vendee-energies-marines", sector: "energy", size: "PME", headcount: 140, city: "La Roche-sur-Yon",
    description: "Bureau d'études et exploitant de parcs éoliens et solaires en Vendée. Ingénierie, maintenance, développement de projets et fonctions support. Croissance forte, alternants recherchés.",
    website: "https://vendee-energies-marines.example.com", foundedYear: 2010,
    technologies: ["cao", "python", "sql", "monitoring", "excel"],
    jobFamilies: ["industrial", "project", "data", "finance", "communication"], hiresApprentices: true, apprenticeCountEstimate: 6, isHiring: true,
    contacts: [{ firstName: "Marc", lastName: "Bertin", jobTitle: "Responsable ingénierie" }, { firstName: "Émilie", lastName: "Charrier", jobTitle: "Gestionnaire RH" }],
    otherLocations: ["Nantes"], jobsCount: 3,
  },
  // ─────────────── RENNES & BRETAGNE ───────────────
  {
    name: "Armor Cyber", slug: "armor-cyber", sector: "tech", size: "PME", headcount: 95, city: "Cesson-Sévigné",
    description: "Pure player cybersécurité de la technopole rennaise : SOC 24/7, audits, pentests et conformité. Partenaire de plusieurs écoles bretonnes, 10 alternants par an.",
    website: "https://armor-cyber.example.com", foundedYear: 2013,
    technologies: ["cybersecurite", "siem", "soc", "pentest", "linux", "python", "iso-27001", "firewall"],
    jobFamilies: ["cyber", "infra", "dev", "sales"], hiresApprentices: true, apprenticeCountEstimate: 10, isHiring: true,
    contacts: [
      { firstName: "Gwenaëlle", lastName: "Le Roux", jobTitle: "Responsable SOC" },
      { firstName: "Mathieu", lastName: "Jouan", jobTitle: "Chargé de recrutement", department: "RH" },
    ],
    jobsCount: 5,
  },
  {
    name: "Ouest Télécom Réseaux", slug: "ouest-telecom-reseaux", sector: "telecom", size: "GE", headcount: 8000, city: "Rennes",
    description: "Opérateur télécom fictif, campus R&D à Rennes et Lannion. Programmes d'alternance dans le développement, les réseaux, la data, le marketing et la relation client.",
    website: "https://ouest-telecom.example.com", foundedYear: 1988,
    technologies: ["java", "python", "reseaux", "kubernetes", "react", "machine-learning", "sql"],
    jobFamilies: ["dev", "infra", "data", "cyber", "marketing", "customer-support", "product", "hr"], hiresApprentices: true, apprenticeCountEstimate: 300, isHiring: true,
    contacts: [
      { firstName: "Solenn", lastName: "Guillou", jobTitle: "Talent Acquisition Manager", department: "RH" },
      { firstName: "David", lastName: "Kerhervé", jobTitle: "Manager équipe cloud", department: "Réseaux & cloud" },
    ],
    otherLocations: ["Lannion", "Brest", "Nantes", "Paris"], jobsCount: 7,
  },
  {
    name: "Rennes Software Factory", slug: "rennes-software-factory", sector: "tech", size: "PME", headcount: 70, city: "Rennes",
    description: "Éditeur de logiciels RH et paie en SaaS. Équipes produit, dev et support à Rennes. Stack .NET / React, pratiques DevOps, alternants intégrés dès la conception.",
    website: "https://rennes-software-factory.example.com", foundedYear: 2009,
    technologies: [".net", "c#", "react", "typescript", "sql-server", "azure", "ci-cd"],
    jobFamilies: ["dev", "product", "customer-support", "sales"], hiresApprentices: true, apprenticeCountEstimate: 5, isHiring: true,
    contacts: [{ firstName: "Florian", lastName: "Hamon", jobTitle: "Engineering Manager" }],
    jobsCount: 3,
  },
  {
    name: "Ille Conseil", slug: "ille-conseil", sector: "consulting", size: "PME", headcount: 60, city: "Rennes",
    description: "Cabinet de conseil en organisation et systèmes d'information pour les collectivités et la santé. Rennes et Nantes. Alternants chefs de projet et consultants juniors.",
    website: "https://ille-conseil.example.com", foundedYear: 2007,
    technologies: ["gestion-de-projet", "agile", "jira", "power-bi", "sql"],
    jobFamilies: ["project", "product", "data", "admin"], hiresApprentices: true, apprenticeCountEstimate: 4, isHiring: true,
    contacts: [{ firstName: "Catherine", lastName: "Riou", jobTitle: "Associée, directrice des opérations" }],
    otherLocations: ["Nantes"], jobsCount: 2,
  },
  {
    name: "Saint-Malo Croisières Demo", slug: "saint-malo-croisieres-demo", sector: "tourism-hospitality", size: "PME", headcount: 180, city: "Saint-Malo",
    description: "Compagnie maritime fictive : liaisons vers les îles anglo-normandes et croisières côtières. Marketing, e-commerce, relation client et comptabilité basés à Saint-Malo.",
    website: "https://smc-demo.example.com", foundedYear: 1990,
    technologies: ["e-commerce", "google-analytics", "crm", "excel", "social-media"],
    jobFamilies: ["marketing", "customer-support", "accounting", "communication"], hiresApprentices: true, apprenticeCountEstimate: 4, isHiring: true,
    contacts: [{ firstName: "Erwan", lastName: "Tanguy", jobTitle: "Responsable marketing" }],
    jobsCount: 2,
  },
  {
    name: "Brest Océan Tech", slug: "brest-ocean-tech", sector: "tech", size: "PME", headcount: 48, city: "Brest",
    description: "Startup brestoise de capteurs et logiciels pour l'observation des océans. Embarqué, data et web. Partenariats avec les laboratoires locaux, alternants ingénieurs bienvenus.",
    website: "https://brest-ocean-tech.example.com", foundedYear: 2017,
    technologies: ["python", "c", "electronique", "react", "postgresql", "machine-learning"],
    jobFamilies: ["dev", "data", "industrial", "product"], hiresApprentices: true, apprenticeCountEstimate: 4, isHiring: true,
    contacts: [{ firstName: "Morgane", lastName: "Quéré", jobTitle: "CEO & cofondatrice" }, { firstName: "Loïc", lastName: "Salaün", jobTitle: "Lead développeur" }],
    jobsCount: 3,
  },
  {
    name: "Arsenal Naval Services Demo", slug: "arsenal-naval-services-demo", sector: "aerospace-naval", size: "GE", headcount: 5500, city: "Brest",
    description: "Groupe industriel naval fictif implanté à Brest et Lorient : maintenance et construction de navires. Alternances en ingénierie, production, supply chain, qualité et cybersécurité industrielle.",
    website: "https://ans-demo.example.com", foundedYear: 1631,
    technologies: ["cao", "sap", "cybersecurite", "automatisme", "lean-management", "qualite"],
    jobFamilies: ["industrial", "quality", "logistics", "cyber", "purchasing", "hr", "infra"], hiresApprentices: true, apprenticeCountEstimate: 180, isHiring: true,
    contacts: [{ firstName: "Anne", lastName: "Le Gall", jobTitle: "Responsable recrutement alternance", department: "RH" }],
    otherLocations: ["Lorient"], jobsCount: 5,
  },
  {
    name: "Studio Kelenn", slug: "studio-kelenn", sector: "digital-agency", size: "TPE", headcount: 6, city: "Quimper",
    description: "Studio de design graphique et de communication à Quimper : identités visuelles, sites web et vidéos pour les acteurs culturels bretons.",
    website: "https://studio-kelenn.example.com", foundedYear: 2016,
    technologies: ["figma", "adobe-illustrator", "adobe-photoshop", "adobe-premiere", "wordpress"],
    jobFamilies: ["design", "communication", "marketing"], hiresApprentices: true, apprenticeCountEstimate: 1, isHiring: false,
    contacts: [{ firstName: "Nolwenn", lastName: "Kerbrat", jobTitle: "Fondatrice, directrice artistique" }],
    jobsCount: 1,
  },
  {
    name: "Lorient Agro Marée", slug: "lorient-agro-maree", sector: "food-agri", size: "ETI", headcount: 520, city: "Lorient",
    description: "Transformation et distribution de produits de la mer depuis le port de Lorient. Usine, logistique frigorifique et services commerciaux. Alternants en qualité, logistique, commerce et maintenance.",
    website: "https://lorient-agro-maree.example.com", foundedYear: 1975,
    technologies: ["qualite", "supply-chain", "erp", "excel", "maintenance-industrielle"],
    jobFamilies: ["quality", "logistics", "sales", "industrial", "accounting"], hiresApprentices: true, apprenticeCountEstimate: 15, isHiring: true,
    contacts: [{ firstName: "Fabien", lastName: "Le Corre", jobTitle: "Responsable RH" }],
    jobsCount: 3,
  },
  {
    name: "Golfe Assurances Courtage", slug: "golfe-assurances-courtage", sector: "banking-insurance", size: "PME", headcount: 45, city: "Vannes",
    description: "Courtier en assurances pour les entreprises du Morbihan. Vannes centre-ville. Alternants en gestion de contrats, relation client et commerce.",
    website: "https://golfe-assurances.example.com", foundedYear: 2001,
    technologies: ["crm", "pack-office", "assurance"],
    jobFamilies: ["customer-support", "sales", "admin", "accounting"], hiresApprentices: true, apprenticeCountEstimate: 3, isHiring: true,
    contacts: [{ firstName: "Patrick", lastName: "Le Moal", jobTitle: "Dirigeant" }],
    jobsCount: 2,
  },
  {
    name: "Vannes Numérique", slug: "vannes-numerique", sector: "tech", size: "PME", headcount: 32, city: "Vannes",
    description: "ESN locale du Golfe du Morbihan : développement sur mesure, infogérance et support pour les PME. Alternants développeurs et techniciens systèmes.",
    website: "https://vannes-numerique.example.com", foundedYear: 2008,
    technologies: ["php", "symfony", "vue-js", "linux", "office-365", "support-utilisateur", "reseaux"],
    jobFamilies: ["dev", "infra", "customer-support"], hiresApprentices: true, apprenticeCountEstimate: 3, isHiring: true,
    contacts: [{ firstName: "Sébastien", lastName: "Guégan", jobTitle: "Gérant" }],
    jobsCount: 3,
  },
  {
    name: "Côtes d'Armor Agro Coop", slug: "cotes-d-armor-agro-coop", sector: "food-agri", size: "GE", headcount: 7000, city: "Saint-Brieuc",
    description: "Coopérative agroalimentaire fictive des Côtes-d'Armor : nutrition animale, volailles et produits laitiers. Alternances dans toute la Bretagne en production, qualité, data et fonctions support.",
    website: "https://cda-agro-coop.example.com", foundedYear: 1966,
    technologies: ["sap", "power-bi", "qualite", "supply-chain", "lean-management"],
    jobFamilies: ["quality", "logistics", "data", "industrial", "hr", "finance", "sales"], hiresApprentices: true, apprenticeCountEstimate: 120, isHiring: true,
    contacts: [{ firstName: "Christelle", lastName: "Le Bihan", jobTitle: "Responsable développement RH" }],
    otherLocations: ["Rennes", "Lorient"], jobsCount: 3,
  },
  {
    name: "Lannion Photonique", slug: "lannion-photonique", sector: "industry", size: "PME", headcount: 110, city: "Lannion",
    description: "Fabricant de composants optiques et lasers pour les télécoms et le médical. R&D et production à Lannion. Alternants ingénieurs, techniciens et qualité.",
    website: "https://lannion-photonique.example.com", foundedYear: 1994,
    technologies: ["electronique", "python", "cao", "qualite", "c++"],
    jobFamilies: ["industrial", "quality", "dev", "purchasing"], hiresApprentices: true, apprenticeCountEstimate: 5, isHiring: false,
    contacts: [{ firstName: "Ronan", lastName: "Le Floch", jobTitle: "Directeur industriel" }],
    jobsCount: 2,
  },
  {
    name: "Fougères Logistique Express", slug: "fougeres-logistique-express", sector: "logistics", size: "PME", headcount: 230, city: "Fougères",
    description: "Transporteur et logisticien à Fougères : entrepôts, messagerie et e-logistique pour des e-commerçants bretons. Alternants en exploitation, planification et gestion.",
    website: "https://fougeres-logistique.example.com", foundedYear: 1985,
    technologies: ["supply-chain", "erp", "excel", "gestion-des-stocks"],
    jobFamilies: ["logistics", "admin", "accounting", "sales"], hiresApprentices: true, apprenticeCountEstimate: 6, isHiring: true,
    contacts: [{ firstName: "Céline", lastName: "Louvel", jobTitle: "Responsable exploitation" }],
    jobsCount: 2,
  },
  // ─────────────── PARIS & AUTRES ───────────────
  {
    name: "Hexagone Capital Tech", slug: "hexagone-capital-tech", sector: "banking-insurance", size: "GE", headcount: 12000, city: "Paris",
    description: "Banque d'investissement fictive, siège à La Défense. Alternances en finance de marché, data, développement et conformité. Processus de recrutement en deux entretiens.",
    website: "https://hexagone-capital.example.com", foundedYear: 1985,
    technologies: ["python", "java", "sql", "machine-learning", "excel", "react"],
    jobFamilies: ["finance", "data", "dev", "legal", "cyber"], hiresApprentices: true, apprenticeCountEstimate: 400, isHiring: true,
    contacts: [{ firstName: "Alexandre", lastName: "Fournier", jobTitle: "Campus Recruiter", department: "RH" }],
    jobsCount: 4,
  },
  {
    name: "Pulse Média Group", slug: "pulse-media-group", sector: "media", size: "ETI", headcount: 900, city: "Paris",
    description: "Groupe de médias digitaux fictif : sites d'information, podcasts et régie publicitaire. Alternances en marketing, contenu, data et développement.",
    website: "https://pulse-media.example.com", foundedYear: 2005,
    technologies: ["seo", "google-analytics", "react", "python", "social-media", "content-marketing"],
    jobFamilies: ["marketing", "communication", "data", "dev", "design", "sales"], hiresApprentices: true, apprenticeCountEstimate: 40, isHiring: true,
    contacts: [{ firstName: "Chloé", lastName: "Bernard", jobTitle: "Responsable acquisition de talents" }],
    jobsCount: 4,
  },
  {
    name: "Lumen Énergie Services", slug: "lumen-energie-services", sector: "energy", size: "GE", headcount: 15000, city: "Paris",
    description: "Énergéticien fictif : production, réseaux et services d'efficacité énergétique. Alternances partout en France dans l'ingénierie, la data, l'IT et la relation client.",
    website: "https://lumen-energie.example.com", foundedYear: 1946,
    technologies: ["sap", "python", "power-bi", "thermique", "cao", "java"],
    jobFamilies: ["industrial", "data", "dev", "customer-support", "finance", "project"], hiresApprentices: true, apprenticeCountEstimate: 600, isHiring: true,
    contacts: [{ firstName: "Nadia", lastName: "Aït-Ali", jobTitle: "Chargée de recrutement alternance" }],
    otherLocations: ["Nantes", "Lyon", "Bordeaux", "Lille"], jobsCount: 4,
  },
  {
    name: "Rhône Digital Factory", slug: "rhone-digital-factory", sector: "consulting", size: "ETI", headcount: 2200, city: "Lyon",
    description: "ESN lyonnaise fictive : DevOps, data et applications métier pour l'industrie. Alternances à Lyon, Grenoble et Paris.",
    website: "https://rhone-digital.example.com", foundedYear: 2001,
    technologies: ["java", "kubernetes", "python", "react", "azure", "ci-cd"],
    jobFamilies: ["dev", "infra", "data", "cyber", "product"], hiresApprentices: true, apprenticeCountEstimate: 90, isHiring: true,
    contacts: [{ firstName: "Mehdi", lastName: "Zerrouki", jobTitle: "Talent Acquisition Partner" }],
    otherLocations: ["Grenoble", "Paris"], jobsCount: 3,
  },
  {
    name: "Garonne Aéro Logiciels", slug: "garonne-aero-logiciels", sector: "aerospace-naval", size: "ETI", headcount: 1500, city: "Toulouse",
    description: "Éditeur toulousain fictif de logiciels embarqués et de simulation pour l'aéronautique. Alternances en développement C++, tests et data.",
    website: "https://garonne-aero.example.com", foundedYear: 1998,
    technologies: ["c++", "python", "linux", "tests-logiciels", "git"],
    jobFamilies: ["dev", "industrial", "quality", "data"], hiresApprentices: true, apprenticeCountEstimate: 45, isHiring: true,
    contacts: [{ firstName: "Sandra", lastName: "Vidal", jobTitle: "Chargée de recrutement" }],
    jobsCount: 2,
  },
  {
    name: "Gironde Vins & Négoce", slug: "gironde-vins-negoce", sector: "retail", size: "PME", headcount: 95, city: "Bordeaux",
    description: "Négociant en vins bordelais fictif, export vers 40 pays. Alternances en commerce international, marketing et logistique.",
    website: "https://gironde-vins.example.com", foundedYear: 1932,
    technologies: ["crm", "excel", "e-commerce", "anglais"],
    jobFamilies: ["sales", "marketing", "logistics", "accounting"], hiresApprentices: true, apprenticeCountEstimate: 4, isHiring: true,
    contacts: [{ firstName: "Guillaume", lastName: "Dubourg", jobTitle: "Directeur commercial" }],
    jobsCount: 2,
  },
  {
    name: "Nord Retail Digital", slug: "nord-retail-digital", sector: "ecommerce", size: "ETI", headcount: 1800, city: "Lille",
    description: "Pure player e-commerce lillois fictif : maison et décoration. Alternances en marketing digital, data, logistique et développement.",
    website: "https://nord-retail-digital.example.com", foundedYear: 2008,
    technologies: ["react", "node-js", "sql", "google-analytics", "seo", "sea", "python"],
    jobFamilies: ["marketing", "data", "dev", "logistics", "design"], hiresApprentices: true, apprenticeCountEstimate: 60, isHiring: true,
    contacts: [{ firstName: "Amandine", lastName: "Vasseur", jobTitle: "HR Business Partner" }],
    jobsCount: 3,
  },
  {
    name: "Méditerranée Santé Numérique", slug: "mediterranee-sante-numerique", sector: "health", size: "PME", headcount: 130, city: "Montpellier",
    description: "Éditeur montpelliérain fictif de logiciels pour les hôpitaux. Alternances en développement, support client et qualité logicielle.",
    website: "https://med-sante-numerique.example.com", foundedYear: 2011,
    technologies: ["java", "angular", "sql", "tests-logiciels", "linux"],
    jobFamilies: ["dev", "customer-support", "quality", "product"], hiresApprentices: true, apprenticeCountEstimate: 8, isHiring: true,
    contacts: [{ firstName: "Julien", lastName: "Costa", jobTitle: "Responsable R&D" }],
    jobsCount: 2,
  },
  {
    name: "Alsace Industrie Connectée", slug: "alsace-industrie-connectee", sector: "industry", size: "PME", headcount: 200, city: "Strasbourg",
    description: "Intégrateur strasbourgeois fictif de solutions IoT pour l'industrie 4.0. Alternances en automatisme, data et développement embarqué.",
    website: "https://alsace-industrie.example.com", foundedYear: 2013,
    technologies: ["automatisme", "python", "c", "monitoring", "azure"],
    jobFamilies: ["industrial", "dev", "data", "sales"], hiresApprentices: true, apprenticeCountEstimate: 6, isHiring: false,
    contacts: [{ firstName: "Klaus", lastName: "Meyer", jobTitle: "Directeur général" }],
    jobsCount: 1,
  },
  {
    name: "Riviera Hospitality Group", slug: "riviera-hospitality-group", sector: "tourism-hospitality", size: "ETI", headcount: 1300, city: "Nice",
    description: "Groupe hôtelier fictif de la Côte d'Azur. Alternances en marketing, revenue management, RH et comptabilité au siège niçois.",
    website: "https://riviera-hospitality.example.com", foundedYear: 1979,
    technologies: ["excel", "crm", "social-media", "sage"],
    jobFamilies: ["marketing", "hr", "accounting", "customer-support", "finance"], hiresApprentices: true, apprenticeCountEstimate: 25, isHiring: true,
    contacts: [{ firstName: "Valérie", lastName: "Giordano", jobTitle: "DRH" }],
    jobsCount: 2,
  },
  {
    name: "Alpes Data Lab", slug: "alpes-data-lab", sector: "tech", size: "TPE", headcount: 9, city: "Grenoble",
    description: "Petit cabinet grenoblois fictif de conseil en data science pour l'industrie. Un alternant data par an, encadré directement par les fondateurs.",
    website: "https://alpes-data-lab.example.com", foundedYear: 2020,
    technologies: ["python", "machine-learning", "sql", "power-bi", "dbt"],
    jobFamilies: ["data", "dev"], hiresApprentices: true, apprenticeCountEstimate: 1, isHiring: true,
    contacts: [{ firstName: "Élise", lastName: "Moreau", jobTitle: "Cofondatrice" }],
    jobsCount: 1,
  },
  {
    name: "Marseille Port Logistics", slug: "marseille-port-logistics", sector: "logistics", size: "ETI", headcount: 750, city: "Marseille",
    description: "Opérateur logistique portuaire fictif à Marseille-Fos. Alternances en supply chain, douane, data et QHSE.",
    website: "https://marseille-port-logistics.example.com", foundedYear: 1969,
    technologies: ["supply-chain", "erp", "excel", "power-bi", "qualite"],
    jobFamilies: ["logistics", "quality", "data", "admin", "purchasing"], hiresApprentices: true, apprenticeCountEstimate: 20, isHiring: true,
    contacts: [{ firstName: "Karine", lastName: "Blanc", jobTitle: "Responsable recrutement" }],
    jobsCount: 2,
  },
];
